apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{  .Values.component_name }}
    namespace: "roboshop"
    labels:
        app: {{ .Values.component_name }}
spec:
    replicas: {{ .Values.replicas }}
    selector:
        matchLabels:
            app: {{ .Values.component_name }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: {{ .Values.component_name }}
        spec:
            serviceAccountName: {{ .Values.component_name }}
            containers:
                - name: {{ .Values.component_name }}
                  image: crysis307/{{ .Values.component_name }}:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: {{ .Values.service.targetPort  }}          # <- single source of truth
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.component_name }}
                  resources:
                      requests:
                          cpu: "50m"
                          memory: "256Mi"
                      limits:
                          cpu: "300m"
                          memory: "512Mi"

                  {{- if eq .Values.appName "mongodb" }}
                  {{- include "robo.rediness.mongodb" . | nindent 18 }}  # container child keys -> +10 here
                  {{- else }}
                  {{- include "robo.rediness.frontend" . | nindent 18 }}
                  {{- end }}
