# 00-mongo-ca.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongo-selfsigned
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-ca
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  isCA: true
  commonName: mongodb-ca
  secretName: mongo-ca-secret
  issuerRef:
    name: mongo-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongo-ca-issuer
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ca:
    secretName: mongo-ca-secret
---
# 01-mongo-certs.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-ssl
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: mongodb-ssl
  commonName: mongodb-rs0.default.svc.cluster.local
  dnsNames:
    - mongodb-rs0
    - mongodb-rs0.default
    - mongodb-rs0.default.svc
    - mongodb-rs0.default.svc.cluster.local
  usages: [digital signature, key encipherment, server auth, client auth]
  issuerRef:
    name: mongo-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-ssl-internal
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: mongodb-ssl-internal
  commonName: mongodb-rs0.default.svc.cluster.local
  dnsNames:
    - mongodb-rs0
    - mongodb-rs0.default
    - mongodb-rs0.default.svc
    - mongodb-rs0.default.svc.cluster.local
  usages: [digital signature, key encipherment, server auth, client auth]
  issuerRef:
    name: mongo-ca-issuer
    kind: Issuer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: percona-server-mongodb-operator
#  annotations:
#    argocd.argoproj.io/sync-wave: "-1"
  labels:
    name: percona-server-mongodb-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: percona-server-mongodb-operator
    app.kubernetes.io/name: percona-server-mongodb-operator
    app.kubernetes.io/part-of: percona-server-mongodb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: percona-server-mongodb-operator
  template:
    metadata:
      labels:
        name: percona-server-mongodb-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: percona-server-mongodb-operator
        app.kubernetes.io/name: percona-server-mongodb-operator
        app.kubernetes.io/part-of: percona-server-mongodb-operator
    spec:
      serviceAccountName: percona-server-mongodb-operator
      containers:
        - name: percona-server-mongodb-operator
          image: perconalab/percona-server-mongodb-operator:main
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          command:
            - percona-server-mongodb-operator
          env:
            - name: LOG_STRUCTURED
              value: 'false'
            - name: LOG_LEVEL
              value: INFO
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: percona-server-mongodb-operator
            - name: RESYNC_PERIOD
              value: 5s
            - name: DISABLE_TELEMETRY
              value: "false"
            - name: MAX_CONCURRENT_RECONCILES
              value: "1"
---

apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb
  namespace: default
#  annotations:
#    argocd.argoproj.io/sync-wave: "2"
spec:
  crVersion: 1.16.1
  # image = the mongod server image (not the operator)
  image: percona/percona-server-mongodb:6.0

  # operatorImage = operator init-container image (use the stable operator tag you patched to)
  operatorImage: percona/percona-server-mongodb-operator:1.16.1

  allowUnsafeConfigurations: false
  updateStrategy: RollingUpdate


  replsets:
    - name: rs0
      size: 2

      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      podDisruptionBudget:
        minAvailable: 1
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
      expose:
        enabled: false # ClusterIP only
#  users:
#    - name: catalogue_user
#      db: admin
#      passwordSecretRef:
#        name: catalogue-user-pass     # K8s Secret containing key "password"
#        key: password
#      roles:
#        - db: catalogue
#          name: readWrite

  secrets:
    ssl: mongodb-ssl
    sslInternal: mongodb-ssl-internal
#    users: psmdb-users

#  kubectl create secret generic catalogue-user-pass --from-literal=password='catalogue_pass'

## Enable percona backup manager (PBM)
#  backup:
#    enabled: true
#    image: percona/percona-backup-mongodb:2.5.1
#    storages:
#      s3-us:
#        type: s3
#        s3:
#          bucket: $(S3_BUCKET)
#          region: $(S3_REGION)
#          credentialsSecret: psmdb-backup-s3
#  # If using Pod Identity, drop credentialsSecret and rely on IAM
#    tasks:
#      - name: nightly-snapshots
#        enabled: true
#        schedule: "0 18 * * *" # 11:30 PM IST backups (18:00 UTC)
#        keep: 7
#        type: snapshot
#        storageName: s3-us


  # Metrics for Prometheus
  sharding:
      enabled: false
#  mongod:
#      net:
#        port: 27017
#      security:
#        enableEncryption: true
#        encryptionKeySecret: "" # leave empty to auto-manage; for KMIP/HSM, set accordingly
#  pmm:
#      enabled: false
#  monitoring:
#      enabled: true

#
#  kubectl -n default get deploy psmdb-operator -o jsonpath='{.spec.template.spec.containers[0].image}'; echo
#  kubectl get crd perconaservermongodbs.psmdb.percona.com -o jsonpath='{.spec.versions[*].name}'; echo
#  kubectl get crd perconaservermongodbs.psmdb.percona.com -o yaml | yq '.spec.versions[].schema.openAPIV3Schema.properties.spec.properties | keys'
#

