

apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb
  namespace: default
spec:
  crVersion: 1.16.1
  image: percona/percona-server-mongodb:6.0
  allowUnsafeConfigurations: false
  updateStrategy: RollingUpdate

  replsets:
    - name: rs0
      size: 2

      podDisruptionBudget:
        minAvailable: 2
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
      expose:
        enabled: false # ClusterIP only

  secrets:
    users: psmdb-users-v115


## Enable percona backup manager (PBM)
#  backup:
#    enabled: true
#    image: percona/percona-backup-mongodb:2.5.1
#    storages:
#      s3-us:
#        type: s3
#        s3:
#          bucket: $(S3_BUCKET)
#          region: $(S3_REGION)
#          credentialsSecret: psmdb-backup-s3
#  # If using Pod Identity, drop credentialsSecret and rely on IAM
#    tasks:
#      - name: nightly-snapshots
#        enabled: true
#        schedule: "0 18 * * *" # 11:30 PM IST backups (18:00 UTC)
#        keep: 7
#        type: snapshot
#        storageName: s3-us


  # Metrics for Prometheus
  sharding:
      enabled: false
#  mongod:
#      net:
#        port: 27017
#      security:
#        enableEncryption: true
#        encryptionKeySecret: "" # leave empty to auto-manage; for KMIP/HSM, set accordingly
#  pmm:
#      enabled: false
#  monitoring:
#      enabled: true