apiVersion: batch/v1
kind: Job
metadata:
  name: cataloguedb-seed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: crysis307/mongodb:latest
          command: ["bash","-lc"]
          args:
            - |
              set -euo pipefail
              ls -lah /docker-entrypoint-initdb.d
              mongosh "$MONGO_URL" </docker-entrypoint-initdb.d/master-data.js
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: catalogue-mongo-url
                  key: MONGO_URL
          # mount /seed if your image expects external files

---