apiVersion: batch/v1
kind: Job
metadata:
  name: cataloguedb-seed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: crysis307/mongodb:latest
          command: ["bash","-lc"]
          args:
            - |
              set -euo pipefail
              mongosh "$MONGO_URL" --file /seed/init.js
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: catalogue-mongo-url
                  key: MONGO_URL
          # mount /seed if your image expects external files

---