apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://learn-vault.mikeydevops1.online"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psmdb-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: psmdb-users
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kv/psmdb
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catalogue-mongo-url
  namespace: roboshop
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: catalogue-mongo-url
    template:
      engineVersion: v2
      data:
        MONGO_URL: >-
          mongodb://{{ .MONGO_INITDB_ROOT_USERNAME }}:{{ .MONGO_INITDB_ROOT_PASSWORD }}@
          mongodb-rs0.default.svc.cluster.local:27017/catalogue?replicaSet=rs0
  dataFrom:
    - extract:
        key: kv/psmdb

#    - secretKey: MONGODB_USER_ADMIN_USER
#      remoteRef:
#          key: kv/psmdb/users
#          property: MONGODB_USER_ADMIN_USER
#    - secretKey: MONGODB_USER_ADMIN_PASSWORD
#      remoteRef:
#          key: kv/psmdb/users
#          property: MONGODB_USER_ADMIN_PASSWORD
##    - secretKey: MONGODB_BACKUP_USER
##      remoteRef:
##          key: kv/psmdb/users
##          property: MONGODB_BACKUP_USER
##    - secretKey: MONGODB_BACKUP_PASSWORD
##      remoteRef:
##          key: kv/psmdb/users
##          property: MONGODB_BACKUP_PASSWORD
#    - secretKey: MONGODB_URI
#      remoteRef:
#        key: kv/psmdb/users
#        property: MONGODB_URI

#    MONGO_INITDB_ROOT_USERNAME: admin
#    MONGO_INITDB_ROOT_PASSWORD: admin123
#    MONGO_INITDB_DATABASE: catalogue

